name: Build Latex
run-name: Build latest ${{ github.event.pull_request.base.ref }}
on:
  pull_request_target:
    types: [opened]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: EmanueleMason-${{ github.event.pull_request.base.ref }}
          path: main.pdf
   